### ISSUE TITLE
Help with pocketsphinx installation

### ISSUE THREAD

**Issue by jjwang** [respeaker/Alexa#13]
When I run pip install pocketsphinx, it always failed.  How can I run this demo?

**Comment by jjwang** [comment]
`root@ReSpeaker:~# pip install pocketsphinx
Downloading/unpacking pocketsphinx
  Downloading pocketsphinx-0.1.3.zip (29.3MB): 29.3MB downloaded
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/req.py", line 1197, in prepare_files
    do_download,
  File "/usr/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/req.py", line 1375, in unpack_url
    self.session,
  File "/usr/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/download.py", line 582, in unpack_http_url
    unpack_file(temp_location, location, content_type, link)
  File "/usr/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/util.py", line 621, in unpack_file
    unzip_file(filename, location, flatten=not filename.endswith(('.pybundle', '.whl')))
  File "/usr/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg/pip/util.py", line 495, in unzip_file
    data = zip.read(name)
  File "/usr/lib/python2.7/zipfile.py", line 935, in read
    return self.open(name, "r", pwd).read()
  File "/usr/lib/python2.7/zipfile.py", line 630, in read
    data = self.read1(n)
  File "/usr/lib/python2.7/zipfile.py", line 665, in read1
    data = self._fileobj.read(nbytes)
MemoryError

Storing debug log for failure in /root/.pip/pip.log`

**Comment by xiongyihui** [comment]
pocketsphinx is already installed on respeaker
