### ISSUE TITLE
Issue when to authorize the application

### ISSUE THREAD

**Issue by jjwang** [respeaker/Alexa#14]
Thanks for your reply!  Then when I want to authorize the application according to the following steps:

1. Run alexa or /etc/init.d/alexa start to start Alexa Voice Service
2. At the first time, you need to authorize the application. Connect ReSpeaker's Access Point, go to http://192.168.100.1:3000 and tt will redirect you to Amazon to sign up or login in.

Alexa prompts:

`Traceback (most recent call last):
  File "/usr/bin/alexa", line 369, in <module>
    main()
  File "/usr/bin/alexa", line 341, in main
    mic = Microphone(quit_event=quit_event)
  File "/usr/lib/python2.7/site-packages/respeaker/microphone.py", line 67, in __init__
    pixel_ring.set_color(rgb=0x400000)
  File "/usr/lib/python2.7/site-packages/respeaker/pixel_ring.py", line 19, in set_color
    self.write(0, [self.mono_mode, rgb & 0xFF, (rgb >> 8) & 0xFF, (rgb >> 16) & 0xFF])
  File "/usr/lib/python2.7/site-packages/respeaker/pixel_ring.py", line 58, in write
    self.hid.write(packet)
  File "/usr/lib/python2.7/site-packages/respeaker/usb_hid/pyusb_backend.py", line 162, in write
    self.dev.ctrl_transfer(bmRequestType, bmRequest, wValue, wIndex, data)
  File "/usr/lib/python2.7/site-packages/usb/core.py", line 1034, in ctrl_transfer
    self._ctx.managed_claim_interface(self, interface_number)
  File "/usr/lib/python2.7/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/usb/core.py", line 167, in managed_claim_interface
    self.backend.claim_interface(self.handle, i)
  File "/usr/lib/python2.7/site-packages/usb/backend/libusb1.py", line 818, in claim_interface
    _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
  File "/usr/lib/python2.7/site-packages/usb/backend/libusb1.py", line 602, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 16] Resource busy
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/respeaker/usb_hid/pyusb_backend.py", line 64, in rx_task
    self.rcv_data.append(self.ep_in.read(self.ep_in.wMaxPacketSize, -1))
  File "/usr/lib/python2.7/site-packages/usb/core.py", line 402, in read
    return self.device.read(self, size_or_buffer, timeout)
  File "/usr/lib/python2.7/site-packages/usb/core.py", line 975, in read
    intf, ep = self._ctx.setup_request(self, endpoint)
  File "/usr/lib/python2.7/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/usb/core.py", line 216, in setup_request
    self.managed_claim_interface(device, intf)
  File "/usr/lib/python2.7/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/usb/core.py", line 167, in managed_claim_interface
    self.backend.claim_interface(self.handle, i)
  File "/usr/lib/python2.7/site-packages/usb/backend/libusb1.py", line 818, in claim_interface
    _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
  File "/usr/lib/python2.7/site-packages/usb/backend/libusb1.py", line 602, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
USBError: [Errno 16] Resource busy`

**Comment by jjwang** [comment]
Why does set_color() report error?

**Comment by xiongyihui** [comment]
Maybe the usb device is used by other device.  Try `/etc/init.d/mopidy disable && /etc/init.d/mopidy stop`.
You can run `alexa` without the mic array.
