### ISSUE TITLE
Errno -9998

### ISSUE THREAD

**Issue by ricardogo** [respeaker/Alexa#3]
Brand new ReSpeaker, trying to run Alexa on it and getting the following error:
```
root@ReSpeaker:/tmp# alexa
INFO:root:
INFO:root:Go to http://192.168.100.1:3000 to sign up or login Alexa Voice Service
Expression 'parameters->channelCount <= maxChans' failed in 'src/hostapi/alsa/pa_linux_alsa.c', l
Expression 'ValidateParameters( inputParameters, hostApi, StreamDirection_In )' failed in 'src/ho
Traceback (most recent call last):
  File "/usr/bin/alexa", line 288, in <module>
    main()
  File "/usr/bin/alexa", line 262, in main
    mic = Microphone(quit_event=quit_event)
  File "/usr/lib/python2.7/site-packages/respeaker/microphone.py", line 89, in __init__
    input_device_index=self.device_index,
  File "/usr/lib/python2.7/site-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
IOError: [Errno -9998] Invalid number of channels
```

**Comment by xiongyihui** [comment]
```
/etc/init.d/mopidy stop
/etc/init.d/mopidy disable    # disable to auto-run
```

**Comment by ricardogo** [comment]
Fixed it! Thank you.
Since this happened as I was following the getting started guide, a reference to stopping mopidy will save some trouble to newbies like myself!
Looking forward for some more tinkering :)
